FROM node:22-alpine

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1


COPY --chown=node:node package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 3000

CMD ["npm", "run", "dev"]