# 1. Build Stage
FROM node:20-alpine AS builder

WORKDIR /app

# Install dependencies (cached if package.json doesn't change)
COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

# Copy source code
COPY . .

# Generate Prisma Client & Build the NestJS app
RUN npx prisma generate
RUN npm run build


# 2. Production Stage (Smaller image, secure)
FROM node:20-alpine

WORKDIR /app

# Copy only necessary files from builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/src/generated ./src/generated
COPY --from=builder /app/tsconfig.json ./tsconfig.json

# Copy entrypoint script
COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh

# Expose the API port
EXPOSE 3000

# Use entrypoint script 
ENTRYPOINT ["./docker-entrypoint.sh"]